/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcial;

import java.awt.Color;
import java.util.UUID;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import parcial.controller.AsociadoController;
import parcial.model.Asociado;
import parcial.model.Cuota;
import parcial.model.Prestamo;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sala7
 */
public class VistaAsociado extends javax.swing.JFrame {

    AsociadoController totalp = new AsociadoController();
    Vector<Cuota> cTemp = new Vector();
    Asociado a_sel = new Asociado();

    /**
     * Creates new form VistaAsociado
     */
    public VistaAsociado() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        //asignando datos quemados
        quemados();
        Listar();
    }
   

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_asociados = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_proyectar = new javax.swing.JButton();
        btn_aprobar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Asociado = new javax.swing.JTextField();
        txt_valor = new javax.swing.JTextField();
        txt_plazo = new javax.swing.JTextField();
        txt_interes = new javax.swing.JTextField();
        txt_valorTotal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_prestamos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Mincho Demibold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Asociado");

        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl_asociados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_asociados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_asociadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_asociados);
        if (tbl_asociados.getColumnModel().getColumnCount() > 0) {
            tbl_asociados.getColumnModel().getColumn(0).setResizable(false);
            tbl_asociados.getColumnModel().getColumn(1).setResizable(false);
            tbl_asociados.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_proyectar.setText("PROYECTAR");
        btn_proyectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proyectarActionPerformed(evt);
            }
        });

        btn_aprobar.setText("APROBAR");
        btn_aprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aprobarActionPerformed(evt);
            }
        });

        jLabel2.setText("Asociado");

        jLabel3.setText("Valor");

        jLabel4.setText("Plazo");

        jLabel5.setText("Interes");

        jLabel6.setText("Valor Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_valor, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(txt_plazo)
                    .addComponent(txt_interes)
                    .addComponent(txt_valorTotal)
                    .addComponent(txt_Asociado))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_proyectar)
                    .addComponent(btn_aprobar))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Asociado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_proyectar)
                    .addComponent(jLabel4)
                    .addComponent(txt_plazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_interes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_aprobar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbl_prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ncuotas", "ValorCuota", "ValorPagar", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_prestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_prestamosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_prestamos);
        if (tbl_prestamos.getColumnModel().getColumnCount() > 0) {
            tbl_prestamos.getColumnModel().getColumn(0).setResizable(false);
            tbl_prestamos.getColumnModel().getColumn(1).setResizable(false);
            tbl_prestamos.getColumnModel().getColumn(2).setResizable(false);
            tbl_prestamos.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1AncestorAdded

    private void btn_proyectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proyectarActionPerformed
        try {
            Asociado a1 = totalp.getList_asociados().get(tbl_asociados.getSelectedRow());

            double valor = Double.parseDouble(txt_valor.getText());
            double interes = Double.parseDouble(txt_interes.getText());
            double plazo = Double.parseDouble(txt_plazo.getText());

            if (plazo >= 1 && plazo <= 48) {
                if (interes >= 1 && interes <= 8) {
                    double valorTotal = valor + (valor * interes / 100);
                    if ((4 * a1.getSalario()) > valorTotal) {
                        txt_valorTotal.setText(valorTotal + "");
                        double valorCuota = valorTotal / plazo;
                        Prestamo p1 = new Prestamo(
                                valor,
                                interes,
                                plazo,
                                a1
                        );

                        double valorPagar = Math.round(valorTotal - valorCuota);

                        totalp.cuotas((int) plazo, 0, valorPagar, Math.round(valorCuota), valorTotal, p1, cTemp);
                        a_sel = a1;
                        btn_aprobar.setEnabled(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "El valor total excede 4 veces el salario del asociado");
                        block();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El interes debe estar entre 1 y 8 por ciento");
                    block();
                }
            } else {
                JOptionPane.showMessageDialog(null, "El plazo debe estar entre 1 y 48 meses");
                block();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error, revise sus datos");
        }

    }//GEN-LAST:event_btn_proyectarActionPerformed

    private void btn_aprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aprobarActionPerformed
        totalp.igualar(0, totalp.getList_prestamos(), cTemp);

        totalp.cambiarEst_prestamo(0, a_sel, "conPrestamo");
        listar2(a_sel);
        cTemp.clear();
        btn_aprobar.setEnabled(false);
        vaciar();
        stop(false);

    }//GEN-LAST:event_btn_aprobarActionPerformed

    private void tbl_asociadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_asociadosMouseClicked
        vaciar();
        a_sel = totalp.getList_asociados().get(tbl_asociados.getSelectedRow());
        txt_Asociado.setText(a_sel.getNombre());
        btn_proyectar.setEnabled(true);
        if (a_sel.getEstado().equals("sinPrestamo")) {
            stop(true);
        } else if (a_sel.getEstado().equals("conPrestamo")) {
            stop(false);
        }
        listar2(a_sel);

    }//GEN-LAST:event_tbl_asociadosMouseClicked

    private void tbl_prestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_prestamosMouseClicked
         int column = tbl_prestamos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tbl_prestamos.getRowHeight();

        if (row < tbl_prestamos.getRowCount() && row >= 0 && column < tbl_prestamos.getColumnCount() && column >= 0) {
            Object value = tbl_prestamos.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("pagar") && boton.getText().equals("Pagar")) {
                    int opc = JOptionPane.showConfirmDialog(null, "Desea pagar la cuota", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    switch (opc) {
                        case 0:


//                            else if (!totalp.getList_prestamos().get(row - 1).isPagada()) {
//                                JOptionPane.showMessageDialog(null, "Debe pagar la anterior");
//                            }
                            break;
                        case 1:
                            System.out.println(row);
                            break;

                    }

                    //EVENTOS ELIMINAR
                }
            }

        }
    }//GEN-LAST:event_tbl_prestamosMouseClicked

     public void block() {
        btn_aprobar.setEnabled(false);
        cTemp.clear();
    }

    public void stop(boolean b) {
        btn_proyectar.setEnabled(b);
        txt_plazo.setEnabled(b);
        txt_interes.setEnabled(b);
        txt_valor.setEnabled(b);
    }

    public void quemados() {
        totalp.getList_asociados().add(new Asociado(UUID.randomUUID() + "", "Hector Herrera", 1000000, "sinPrestamo"));
        totalp.getList_asociados().add(new Asociado(UUID.randomUUID() + "", "Daniela Osorio", 500000, "sinPrestamo"));
        totalp.getList_asociados().add(new Asociado(UUID.randomUUID() + "", "José Chico", 1500000, "sinPrestamo"));
        totalp.getList_asociados().add(new Asociado(UUID.randomUUID() + "", "Christian Castilla", 2500000, "sinPrestamo"));
        totalp.getList_asociados().add(new Asociado(UUID.randomUUID() + "", "Tupac Lopez", 5350000, "sinPrestamo"));
        totalp.getList_asociados().add(new Asociado(UUID.randomUUID() + "", "Indian Malah", 805000, "sinPrestamo"));
    }

    public void vaciar() {
        txt_Asociado.setText("");
        txt_interes.setText("");
        txt_plazo.setText("");
        txt_valor.setText("");
        txt_valorTotal.setText("");
        block();
    }

    public void Listar() {

        listar_asociados(
                totalp.getList_asociados().size(),
                0,
                (DefaultTableModel) tbl_asociados.getModel(),
                totalp.getList_asociados()
        );

    }
    public void listar2(Asociado a1) {

        tbl_prestamos.setDefaultRenderer(Object.class, new render());

        listar_prestamos(
                totalp.getList_prestamos().size(),
                0,
                (DefaultTableModel) tbl_prestamos.getModel(),
                totalp.getList_prestamos(),
                a1
        );
    }
      public static void listar_asociados(int limit, int i, DefaultTableModel tb1, Vector<Asociado> arr) {
        if (i == 0) {
            tb1.setNumRows(0);
        }

        tb1.addRow(new Object[]{
            arr.get(i).getCodigo(),
            arr.get(i).getNombre(),
            arr.get(i).getSalario()
        });

        //incremento
        i++;
        //repetir
        if (i < limit) {
            listar_asociados(limit, i, tb1, arr);
        }
    }

    public static void listar_prestamos(int limit, int i, DefaultTableModel tb1, Vector<Cuota> arr, Asociado a1) {

        if (i == 0) {
            tb1.setNumRows(0);
        }

        if (arr.size() > 0) {

            JButton btnPagar = new JButton((arr.get(i).isPagada()) ? "Pagada" : "Pagar");
            btnPagar.setName("pagar");
            btnPagar.setEnabled(!arr.get(i).isPagada());
            btnPagar.setBackground((arr.get(i).isPagada()) ? Color.green : Color.red);

            if (arr.get(i).getPres1().getA1().getCodigo().equals(a1.getCodigo())) {
                tb1.addRow(new Object[]{
                    arr.get(i).getNcuota(),
                    arr.get(i).getValorCuota(),
                    arr.get(i).getValorPagar(),
                    arr.get(i).getSaldo(),
                    btnPagar
                });
            }
        }
        //incremento
        i++;
        //repetir
        if (i < limit) {
            listar_prestamos(limit, i, tb1, arr, a1);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAsociado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAsociado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAsociado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAsociado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAsociado().setVisible(true);
            }
        });
    }

    DefaultTableModel dtma = new DefaultTableModel();
    DefaultTableModel dtmc = new DefaultTableModel();
    Asociado ast = new Asociado();

//    public void consultar(){
//        
//        for(int i=0;i<){
//            
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aprobar;
    private javax.swing.JButton btn_proyectar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_asociados;
    private javax.swing.JTable tbl_prestamos;
    private javax.swing.JTextField txt_Asociado;
    private javax.swing.JTextField txt_interes;
    private javax.swing.JTextField txt_plazo;
    private javax.swing.JTextField txt_valor;
    private javax.swing.JTextField txt_valorTotal;
    // End of variables declaration//GEN-END:variables
}
